Task 1: Creating and Manipulating Arrays

In [2]:
import numpy as np

In [3]:
my_array = np.array([1,2,3,4,5,6,7,8,9,10])
print(my_array)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
random_array = np.random.randint(1, 21, size=(3,4))
print(random_array)

[[20 15 18  1]
 [ 6  3  6 19]
 [ 4  2  2 19]]


In [8]:
reshaped_array = random_array.reshape(4,3)
print("Reshaped array (4,3): \n", reshaped_array)

Reshaped array (4,3): 
 [[20 15 18]
 [ 1  6  3]
 [ 6 19  4]
 [ 2  2 19]]


In [10]:
flattened_array = random_array.flatten()
print("1D array :", flattened_array)

1D array : [20 15 18  1  6  3  6 19  4  2  2 19]


In [11]:
first_five = flattened_array[:5]
print(first_five)

[20 15 18  1  6]


In [14]:
zero_array = np.zeros((2, 3))
print(zero_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
ones_array = np.ones((3, 2))
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


Task 2: Array Operations

In [6]:
array_1 = np.array([1,2,3,4])
array_2 = np.array([4,5,6,7])

#addition
addition_array = array_1 + array_2
print(addition_array)

#subtraction
sub_array = array_1 - array_2
print("\n", sub_array)

#multiplication
multiply_array = array_1 * array_2
print("\n", multiply_array)

#division
divide_array = array_1 / array_2
print("\n", divide_array)

[ 5  7  9 11]

 [-3 -3 -3 -3]

 [ 4 10 18 28]

 [0.25       0.4        0.5        0.57142857]


In [7]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

dot_product = np.dot(array1, array2)
print(dot_product)

[[19 22]
 [43 50]]


In [8]:
idenrity_matrix = np.eye(3)
print(idenrity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
data = np.random.randint(1, 100, size=(10))

total_sum = np.sum(data)
on_average = np.mean(data)
std_dev = np.std(data)
variance = np.var(data)

print("\n", total_sum, "\n", on_average, "\n", std_dev, "\n", variance)


 352 
 35.2 
 30.7889590600267 
 947.96


Task 3: Boolean Indexing and Filtering


In [11]:
oneD_array = np.random.randint(0,51, size=(15))
print(oneD_array)

[ 3 26  9 23 48 26  6  7 49  6 44 48 16  1 33]


In [13]:
mask = oneD_array > 25

masked_array = oneD_array[mask]
print(masked_array)

[26 48 26 49 44 48 33]


In [15]:
oneD_array[oneD_array < 10] = 10
print(oneD_array)

[10 10 10 10 10 10 10 10 10 10 10 10 10 10 10]


Task 4: Advanced Operations


In [17]:
matrix = np.random.randint(0, 100, size= (5, 5))

min_matrix = np.min(matrix)
max_matrix = np.max(matrix)

print(matrix, "\n", min_matrix, "\n", max_matrix)

[[33 34 77  3 52]
 [40  5 11 66 63]
 [54 15 39 56  3]
 [29 58 69 82 48]
 [25 84 77  6  7]] 
 3 
 84


In [19]:
row_side = np.sum(matrix, axis=1)
column_side = np.sum(matrix, axis=0)
print(row_side, "\n", column_side)

[199 185 167 286 199] 
 [181 196 273 213 173]


In [22]:
arrayOne = np.array([[1,2,3],[4,5,6]])
arrayTwo = np.array([[7,8,9],[3,4,6]])

vertical_stack = np.vstack((arrayOne, arrayTwo))
horizontal_stack = np.hstack((arrayOne, arrayTwo))

print("Vertical stack:\n", vertical_stack)
print("Horizontal stack:\n", horizontal_stack)

Vertical stack:
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [3 4 6]]
Horizontal stack:
 [[1 2 3 7 8 9]
 [4 5 6 3 4 6]]
